---
Name: fastly-httpconfig
After:
  - 'requestprocessors'
---
SilverStripe\Control\Middleware\HTTPCacheControlMiddleware:
  defaultVary:
    Accept-Encoding: true
    X-Forwarded-Proto: true
    X-Forwarded-Protocol: false
    
---
Name: fastly-httpconfig-dev
After: '#httpconfig-dev'
Only:
  environment: dev
---
SilverStripe\Control\Middleware\HTTPCacheControlMiddleware:
  defaultState: 'enabled'
  defaultForcingLevel: 0

---
Name: fastly
---

SilverStripe\Security\Member:
  login_marker_cookie: sslogin

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\Fastly\Extensions\SiteTreeExtension
ContentController:
  extensions:
    - Innoweb\Fastly\Extensions\ContentControllerExtension
SilverStripe\Assets\File:
  extensions:
    - Innoweb\Fastly\Extensions\FileExtension
    
---
Name: fastly-dms
Only:
  classexists: 'DMSDocument'
---
SilverStripe\Assets\File:
  extensions:
    - Innoweb\Fastly\Extensions\DMSFileExtension
Innoweb\DMS\Controller\DMSDocumentController:
  extensions:
    - Innoweb\Fastly\Extensions\DMSDocumentControllerExtension
Innoweb\DMS\Controller\LegacyDMSDocumentController:
  extensions:
    - Innoweb\Fastly\Extensions\DMSDocumentControllerExtension
